### ISSUE TITLE
TransactionalKafkaProducer don't commit offset with empty records

### ISSUE THREAD

**Issue by chernovsa** [fd4s/fs2-kafka#1099]
According to java doc for `TransactionalProducerRecords`, 
`[records](records: Chunk[CommittableProducerRecords[F, K, V]])` can be empty, but nothing is said about committing offset. 
When we check documentation for `CommittableProducerRecords` we get:

`sealed abstract class CommittableProducerRecords[F[_], +K, +V] {`

  `// The records to produce. Can be empty to simply commit the offset. `
  `def records: Chunk[ProducerRecord[K, V]]`

   `// The offset to commit. `
`  def offset: CommittableOffset[F]`
`}`

That said: "The records to produce. Can be empty to simply commit the offset".
For example:
`val offsets = ???`
`val records = CommittableProducerRecords(Chunk.empty, offsets))`

So, It can confuse when you invoke `TransactionalProducerRecords::produce` with records of that type, where you have empty records, and non-empty offsets. Committing offset is expected, but nothing happens. More over, there is no indication about this case after method invokation, that offset have not committed. 
I believe that, my use case is common. 
Lets consider, that you have a Kafka Job application with usual flow like, consuming data from some topic, filtering data, transforming data, and producing to another topic.  U can see, that when filtering step is presented, then nothing to produce can occur in rare cases. And even this case, you still want to commit offset, to save your consuming progress.

**Comment by chernovsa** [comment]
https://github.com/fd4s/fs2-kafka/pull/1100
Please consider to merge this pull request.

**Comment by bplommer** [comment]
Fixed by #1100
