### ISSUE TITLE
CE 3.5.0 async cancelation semantics

### ISSUE THREAD

**Issue by Jasper-M** [fd4s/fs2-kafka#1181]
I think fs2-kafka will require some changes to accommodate the [new async cancelation semantics](https://github.com/typelevel/cats-effect/releases/tag/v3.5.0-RC1) in the upcoming CE 3.5.0.

For instance [this timeout](https://github.com/fd4s/fs2-kafka/blob/v3.0.0-RC1/modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala#L117) will probably be rendered useless. Also I suspect that currently this timeout only cancels the waiting on the callback but will leak the actual hanging commit, which is what those new semantics are guarding against.

**Comment by bplommer** [comment]
Thanks for flagging this! I'm on it.

**Comment by bplommer** [comment]
> Also I suspect that currently this timeout only cancels the waiting on the callback but will leak the actual hanging commit, which is what those new semantics are guarding against.

Yes, you're right - unfortunately I don't think there's anything we can do about that unless we revert to using the `commitSync` method which has an optional timeout parameter.
