### ISSUE TITLE
Question around custom Partition assignments

### ISSUE THREAD

**Issue by bcarter97** [fd4s/fs2-kafka#1199]
Hello, I am trying to create an assignment manually and I've noticed a difference between the FS2 KafkaConsumer and underlying KafkaConsumer with the overload for 

https://github.com/fd4s/fs2-kafka/blob/e4376d1df82c786c11e968b7945639a7addadbdc/modules/core/src/main/scala/fs2/kafka/consumer/KafkaAssignment.scala#L46

I'm not sure why it requires a `NonEmptySet` of partitions, as the underlying consumer does an empty check and calls `unsubscribe` if the partition set is empty:

https://github.com/apache/kafka/blob/4653507926a42dccda5c086fcae6278afcfc53ca/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L1115

```java
if (partitions == null) {
                throw new IllegalArgumentException("Topic partition collection to assign to cannot be null");
            } else if (partitions.isEmpty()) {
                this.unsubscribe();
            }
...
```

Do you think it is required that the Set should be NonEmpty? If the TopicPartitions are incorrect a `java.lang.IllegalStateException: No current assignment` will be thrown by the KafkaConsumer so validating the TopicPartitions Set seems redundant

**Comment by aartigao** [comment]
It's a common (good) API design in Scala. With `NonEmptySet` we put the validation in the signature making an state impossible (in this case, impossible to call the method without elements in the collection). The fact that underlying `KafkaConsumer` throws exception is worse than controlling it without the burden of exceptions.

I can ask the reverse question: why calling `assign` if you don't have actually anything to assign?

**Comment by aartigao** [comment]
Closing the issue. 

Hope the explanation clarifies the intention of the API 🙃

**Comment by bcarter97** [comment]
Yeah it makes sense thanks 😄
