### ISSUE TITLE
Any reason `RebalanceInProgressException` isn't considered in`CommitRecovery.Default`?

### ISSUE THREAD

**Issue by balajirrao** [fd4s/fs2-kafka#1213]
What is the reason `RebalanceInProgressException` not considered retryable in the default `CommitRecovery` ? If we did so, this in combination with `StoredPendingCommit` introduced in https://github.com/fd4s/fs2-kafka/pull/117, should work well right? 🤔

**Comment by aartigao** [comment]
I agree, I don't see a reason to not retry them 👍🏽
