### ISSUE TITLE
upgrade 3.x to CE 3.5.1 / fs2 3.8.0

### ISSUE THREAD

**Issue by samspills** [fd4s/fs2-kafka#1234]
Hello! I'm working on some dependency updates for $work and fs2-kafka is keeping us on cats-effect 3.4.11 (aka before the async cancellation changes) and fs2 3.6.1

I noticed that CE + fs2 upgrades are ignored in the scala-steward dependencies for 3.x, and I found a TODO regarding the update:
https://github.com/fd4s/fs2-kafka/blob/e4376d1df82c786c11e968b7945639a7addadbdc/modules/core/src/main/scala/fs2/kafka/KafkaProducer.scala#L208-L209

Is there a plan or anything in progress for that version bump yet? If not (and if it would be helpful) I could see how far I get and open up a PR? Since they were explicitly ignored I didn't want to jump in, in case I'm missing important context

**Comment by Jasper-M** [comment]
While the CE version hasn't been upgraded yet, the library should already be compatible with the new cancelation stuff, as of #1187.

**Comment by samspills** [comment]
Ah yes, I deployed yesterday with CE 3.5.1 and fs2-kafka 3.0.1 and everything seems to be going well (_touch wood_). I'd still be happy to help with anything if you'd like it :)

**Comment by sergiojoker11** [comment]
My organization is interested on this upgrade as 3.5.1 offers the ability to override `def onCpuStarvationWarn(metrics: CpuStarvationWarningMetrics): IO[Unit]` in IOApp trait which confusingly logs some warning to stderr.

**Comment by aira-xite** [comment]
@aartigao, hi! Thank you for updating the libraries. Are you planning to make a release anytime soon? It seems like a lot of people would be interested in this update.

**Comment by aartigao** [comment]
Yup, that's the intention. But I want to make sure I don't mess with anything and have support from the core maintainers 😅
