### ISSUE TITLE
Performance regression Producer 3.5.0 vs 3.4.0

### ISSUE THREAD

**Issue by atnoya** [fd4s/fs2-kafka#1321]
We have upgraded fs2-kafka to 3.5.0 from 3.4.0, and it seems the performance and CPU usage got a serious hit.

<img width="752" alt="Screenshot 2024-04-24 at 14 23 04" src="https://github.com/fd4s/fs2-kafka/assets/2158738/fd3a23b7-2434-401d-9594-2b478a78b4f5">
<img width="748" alt="Screenshot 2024-04-24 at 14 23 34" src="https://github.com/fd4s/fs2-kafka/assets/2158738/97de1c9a-23df-406d-9054-0c772bf12566">
<img width="490" alt="Screenshot 2024-04-24 at 14 47 37" src="https://github.com/fd4s/fs2-kafka/assets/2158738/725de317-d456-4e7e-afc8-6b031cf3e2df">

In the screenshots above, you can see when we switch back to 3.4.0 at 14:18

Looking at the list of changes between 3.4.0 and 3.5.0, we tried downgrading only `fs-core` to `3.9.4` as we thought could be the root cause, but still got terrible performance.

It looks to me, but I don't know the internals of cats-effect or fs2 that well, that the problem might be in the change from `Sync[F].blocking` to `Sync[F].interruptible`, as from my limited experience, I don't see how any of the other changes could cause this.

I am happy to provide more information if I can. I will try to test my hypothesis above in the meantime. Will report results If I find anything.

**Comment by abestel** [comment]
I reached the exact same conclusion this afternoon, this PR https://github.com/fd4s/fs2-kafka/pull/1126 seems to be the culprit (tested by reverting it and publishing a local version).

**Comment by aartigao** [comment]
Wow... I'm astonished...

**Comment by aartigao** [comment]
I'm also not well versed on the CE internals, and by looking at the docs for [`interruptible`](https://typelevel.org/cats-effect/api/3.x/cats/effect/kernel/Sync.html#interruptible[A](thunk:=%3EA):F[A]) it didn't seem to hurt, that's why I merged that PR 😢 

OFC, I'm going to create a fix for this now, but now I'm really curious of why such a performance drop 🤔 cc @armanbilge was that expected?

**Comment by aartigao** [comment]
Maybe `interruptible` doesn't shift to the blocking pool?

**Comment by atnoya** [comment]
https://github.com/typelevel/cats-effect/blob/769a89ef5d39f35d3a2cd00ffedbd22c91df48cc/core/jvm/src/main/scala/cats/effect/IOFiberPlatform.scala#L28

I can see some complex logic there, including semaphores, AtomicRefs and busy waits not running in the Blocking TP (can explain the CPU increased usage)?

https://github.com/typelevel/cats-effect/blob/769a89ef5d39f35d3a2cd00ffedbd22c91df48cc/core/jvm/src/main/scala/cats/effect/IOFiberPlatform.scala#L177

But it does seem that the action is run in the Blocking TP.

**Comment by atnoya** [comment]
We can possibly open an issue for clarification in the cats-effect repo.

**Comment by atnoya** [comment]
Btw thanks a million for the quick reaction and the release 🙇

**Comment by atnoya** [comment]
Just dropping confirmation, the new release `3.5.1` fixes the issue:
<img width="743" alt="Screenshot 2024-04-25 at 12 34 48" src="https://github.com/fd4s/fs2-kafka/assets/2158738/7ecbad0b-5ddc-4c57-89e1-a61212d4abc3">
<img width="740" alt="Screenshot 2024-04-25 at 12 34 55" src="https://github.com/fd4s/fs2-kafka/assets/2158738/432c95ab-1d79-423a-9a2f-9ff49e676386">
<img width="498" alt="Screenshot 2024-04-25 at 12 35 03" src="https://github.com/fd4s/fs2-kafka/assets/2158738/3d534453-6c0c-4cdf-a8f6-d046a4e7f0f9">

I am good to close the issue. Unless you want to keep it open for tracking the `interruptible` issue.

**Comment by aartigao** [comment]
It's fine to close it. Thank you!
