### ISSUE TITLE
Simplify the definition of CommitRecovery

### ISSUE THREAD

**Issue by vlovgr** [fd4s/fs2-kafka#236]
It would be nice to explore if we can change the definition of `CommitRecovery` to something along the following lines. `ConsumerSettings` could then accept an `F[CommitRecovery[F]]`, and the recovery functions are then less constrained in their implementation.

```scala
abstract class CommitRecovery[F[_]] {
  def recoverCommitWith(
    offsets: Map[TopicPartition, OffsetAndMetadata],
    commit: F[Unit]
  ): Throwable => F[Unit]
}
```

**Comment by lewisjkl** [comment]
I’ll take a look at this!

**Comment by lewisjkl** [comment]
I may be missing something here, but it seems like this change is going to cause both `Jitter` and `Timer` to be required by all callers of `CommitRecovery#Default`.

```scala
def Default[F[_]](
    implicit F: MonadError[F, Throwable],
    jitter: Jitter[F],
    timer: Timer[F]
  ): CommitRecovery[F]
```

This is assuming that the new `CommitRecovery` looks like:

```scala
abstract class CommitRecovery[F[_]] {
  def recoverCommitWith(
    offsets: Map[TopicPartition, OffsetAndMetadata],
    commit: F[Unit]
  ): Throwable => F[Unit]
}
```

Do we think it is alright to "leak" `Jitter` and `Timer` around the codebase? Or is there another way you had in mind for doing this?

**Comment by vlovgr** [comment]
Thanks for taking a look at this @lewisjkl! The default `CommitRecovery` would only really be used in `ConsumerSettings`, where a default `Jitter` instance could be created. I think we can't get away from `ConsumerSettings` requiring `Timer` though, even though it might not be used (as is the case when a custom `CommitRecovery` is used). Sounds like maybe we should let it stay as-is. WDYT?

**Comment by lewisjkl** [comment]
Yeah, it seems like the benefit of changing it to be `CommitRecovery[F[_]]` will cause more difficulty in working with the API than it is worth. I agree that it should stay as-is, at least for now 🙂
