### ISSUE TITLE
Add missing extractors for most data types

### ISSUE THREAD

**Issue by vlovgr** [fd4s/fs2-kafka#237]
Most provided data types which provide an `apply` function should also provide an `unapply` function.

For example, `unapply` for `ProducerResult` would look like:

```scala
object ProducerResult {
  def unapply[K, V, P](result: ProducerResult[K, V, P]): Some[(Chunk[(ProducerRecord[K, V], RecordMetadata)], P)] =
    Some((result.records, result.passthrough))
}
```

which would allow us to `match` on `ProducerResult`s (note the `Some` rather than `Option` in the return type, which is required for exhaustivity checking).

**Comment by lewisjkl** [comment]
I will take a look at this one next 👍
