### ISSUE TITLE
Able to Access KStream functionality from Kafka-Streams

### ISSUE THREAD

**Issue by MarkRBM** [fd4s/fs2-kafka#258]
In fs2-kafka is there anyway to access or mimic the behavior provided by this datastructure from Kafka streams https://docs.confluent.io/current/streams/concepts.html#ktable ?

**Comment by vlovgr** [comment]
Hi @MarkRBM! Sorry it's taken me a while to get around to this. KSQL and Kafka Streams are not supported, and there is currently no plans to support them within the scope of this project.
