### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by vlovgr** [fd4s/fs2-kafka#278]
FS2 Kafka is already being used in production across several companies. We should therefore release a v1.0.0 to more explicitly communicate binary compatibility. Before committing to v1.0.0, it might be a good idea to squeeze in a few changes.

Some proposed changes as follows.
- [x] ~Coordinate with the v1.0.0 release of Vulcan (https://github.com/fd4s/vulcan/issues/102).~
- [x] ~Address the issues assigned to the [v1.0.0 milestone](https://github.com/fd4s/fs2-kafka/milestone/1).~

**Comment by jgagnon1** [comment]
This would be useful so I can use the project with `vulcan-generic` from fd4s repository. Any timeline for this ?

**Comment by vlovgr** [comment]
> This would be useful so I can use the project with `vulcan-generic` from fd4s repository. Any timeline for this ?

@jgagnon1 I'm hoping we can manage to get v1.0.0 out in the next couple of weeks. Note that you can use `fs2-kafka-vulcan` with vulcan 0.3.x without issues in the meantime.

**Comment by vlovgr** [comment]
Released: https://github.com/fd4s/fs2-kafka/releases/tag/v1.0.0
