### ISSUE TITLE
Unsubscribe from specific topic

### ISSUE THREAD

**Issue by s5bug** [fd4s/fs2-kafka#317]
I have multiple nodes dedicated to producing to topics that follow the form `region-{n}-{m}`. I'm subscribing to specific `region`s based on my application's state, but I want it to be able to unsubscribe from specific `region`s as well.

I'm entirely new to Kafka, so if I should take a different approach to this than topics I'm all ears.

**Comment by bplommer** [comment]
As far as I can tell, this kind of incremental subscription management isn't supported by the underlying Kakfa library (or, presumably, by the Kafka protocol). Subscribing a consumer to a specific topic will cancel the previous subscription. Could you provide a bit more detail about your use case?

**Comment by sorenbug** [comment]
I honestly have completely forgotten and I think I was using Kafka wrong. When I try to do distributed things again, I'm gonna do some research into Kafka and Pulsar.

I think the use was for some sort of proxy nodes that needed to "shift" what regions they were subscribed to to be the most performant for users, but I'm not sure.
