### ISSUE TITLE
Consumer never recovers from revoked fetch

### ISSUE THREAD

**Issue by olib963** [fd4s/fs2-kafka#366]
Hello, thanks for all your awesome work on this library! We have been using it for a while and it is fab. We have recently had an issue where we see this log message:

```
Revoked previous fetch for partition [$topic-$partition] in stream with id [$id].
```

which I believe relates to [this function](
https://github.com/fd4s/fs2-kafka/blob/ee2aac75a46219f4009bd5d3de7e5414e8687612/modules/core/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala#L195).

Our problem is that after this occurs the consumer never starts re-consuming from that partition and it is not rebalanced to another in the consumer group. We only start to make progress after manually restarting the process causing the issue.

Is there any way to recover from this issue? Is there something about the design on fs2-kafka we can adjust to account for this or is there already a way to handle this client side?

**Comment by bplommer** [comment]
Sorry for the lack of any response to this - would you be able to provide a minimal example to reproduce this?

**Comment by olib963** [comment]
Sorry I should have come back to this, this seemed to be an intermittent networking problem on our end that coincided with these logs. It's resolved itself now.

**Comment by chain-alex** [comment]
This exact behavior seems to be occurring for us as well. We see this log, then we need to manually restart this consumer in order for it to continue to process.
