### ISSUE TITLE
Move P type in ProducerResult, ProducerRecords and TransactionalProducerRecords to the left

### ISSUE THREAD

**Issue by LMnet** [fd4s/fs2-kafka#410]
In [this](https://github.com/fd4s/fs2-kafka/pull/409) pull request some of the library types got `Traverse` and `Bitraverse` instances. This improves their usability. 

Unfortunately, there are a few types that could benefit from these instances too, but they implementation does not give an opportunity to implement these instances. I'm talking about `ProducerResult`, `ProducerRecords`, and `TransactionalProducerRecords`. They all have a `P` (passthrough) type as the rightmost type. Scala's partial unification is right-biased. And because of this, we can only implement `Traverse` or `Bitraverse` for the rightmost types. Which would be inconsistent with all other types instances.

Because of this, I want to move `P` type to the left and after that implement `Traverse` and `Bitraverse` instances for `ProducerResult`, `ProducerRecords`, and `TransactionalProducerRecords`. This change would be not source compatible with the current codebase, so it could be done only in 2.0.0 version.

**Comment by bplommer** [comment]
Resolved by #466
