### ISSUE TITLE
1.2.0 regression: lost guarantee of order for producer

### ISSUE THREAD

**Issue by LMnet** [fd4s/fs2-kafka#477]
It looks like [this](https://github.com/fd4s/fs2-kafka/pull/418/files#diff-c4655864f9261fc7a30abdbdd8df44a5d4ed192dcdba30f5ab511b4f7dc8cb8fR112-R124) pull request slightly change the semantic of producing in fs2-kafka. Java Kafka producer gives a guarantee, that messages will be produced in the same order as `producer.send` calls. In the version of fs2-kafka before 1.2.0, this guarantee was maintained. But after 1.2.0 some of my tests, which rely on this guarantee fail.

I suppose it's somehow related to the `F.async`.

**Comment by vlovgr** [comment]
Nice spot! Looks like an oversight in the pull request. It happens because `start` does not guarantee ordering. We might have to go back to require `ConcurrentEffect` again, unless you have some other idea @bplommer?

**Comment by bplommer** [comment]
> Nice spot! Looks like an oversight in the pull request. It happens because `start` does not guarantee ordering. We might have to go back to require `ConcurrentEffect` again, unless you have some other idea @bplommer?

Not off the top of my head.

If I'm understanding this correctly, the problem is that the outer `F` in `produce` is supposed to block on queueing the message but no longer does, is that right?

**Comment by LMnet** [comment]
>  the outer F in produce is supposed to block on queueing the message but no longer does, is that right?

Looks like this.

It's pretty easy to write a reproducible test for this behavior. But unfortunately, I will be busy in the near future and will not be able to handle this problem.

**Comment by bplommer** [comment]
Thanks - I'm looking into this now. In the meantime, I've added a notice to the top of the 1.2.0 release notes.

**Comment by LMnet** [comment]
@bplommer minor nitpick — link from the release notes doesn't point to this issue.

**Comment by bplommer** [comment]
> @bplommer minor nitpick — link from the release notes doesn't point to this issue.

Thanks! I've fixed it.

**Comment by SystemFw** [comment]
Do we have a test for this?

**Comment by bplommer** [comment]
> Do we have a test for this?

Yes, I added one in #478
