### ISSUE TITLE
Incorporate code from ciris-aiven-kafka for setting up SSL certs from strings

### ISSUE THREAD

**Issue by bplommer** [fd4s/fs2-kafka#521]
At work we're using [ciris-aiven-kafka](https://github.com/ovotech/ciris-aiven-kafka) to load SSL certificates from strings, even in services that don't otherwise use Ciris. I think we should provide this functionality in fs2-kafka, without depending on Ciris or a particular way of loading config values.

[The fact that ciris-aiven-kafka is hosted on Bintray is probably another reason to do this](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

**Comment by agustafson** [comment]
Will take a look @bplommer

**Comment by bplommer** [comment]
Resolved by #530
