### ISSUE TITLE
3.x milestone with cats-effect 3.0.0

### ISSUE THREAD

**Issue by bplommer** [fd4s/fs2-kafka#559]
Waiting on a new fs2 release

**Comment by catostrophe** [comment]
It's out. fs2-kafka v3.0.0-M2 doesn't work with CE 3.0.0 due to bin incompat changes in CE3

**Comment by bplommer** [comment]
I'll put out a new release this evening.

**Comment by catostrophe** [comment]
Thanks!

**Comment by bplommer** [comment]
3.0.0-M3 is out.
