### ISSUE TITLE
Add ProtobufSettings for Registry

### ISSUE THREAD

**Issue by brbrown25** [fd4s/fs2-kafka#634]
It would be nice if protobuf was supported in addition to Avro, something similar to https://github.com/fd4s/fs2-kafka/blob/series/2.x/modules/vulcan/src/main/scala/fs2/kafka/vulcan/AvroSettings.scala. If you're interested, I'd be willing to take a crack at this!

**Comment by bplommer** [comment]
Following discussion in #641, I’m closing this in favour of Protobuf support being provided by a separately maintained library.
