### ISSUE TITLE
Adding dependency on fs2-kafka-vulcan fails to resolve

### ISSUE THREAD

**Issue by Daenyth** [fd4s/fs2-kafka#660]
When you add the dependency on fs2-kafka-vulcan to your project, it won't resolve unless you have the confluent resolver added;
```scala
resolvers += "confluent" at "https://packages.confluent.io/maven/",
```

Otherwise, you get

> ResolveException: Error downloading io.confluent:kafka-avro-serializer:6.1.1

This should be added to the docs for the vulcan integration

**Comment by bplommer** [comment]
Good catch! Would you mind opening a PR?
