### ISSUE TITLE
Avro union type issue with Schema Registry

### ISSUE THREAD

**Issue by calvinlfer** [fd4s/fs2-kafka#689]
Hey there,

I accidentally posted [this issue](https://github.com/fd4s/vulcan/issues/381) in the vulcan project instead of this one so I'm cross-posting the issue here for greater visibility. The gist of it is that you cannot use sealed traits (union types) as top-level subjects when publishing to Kafka and I think this is because of Confluent's underlying serialization mechanism not having proper support for union types. I managed to work around this by using a record containing a schema but I was wondering if this is something we could improve upon since Confluent's Schema Registry does seem to correctly support union types but I believe its the Java Serializer from Confluent that has this limitation.

Thank you so much for all your hard work and this amazing library

**Comment by bplommer** [comment]
Hi @calvinlfer, sorry for the very slow reply! Reimplementing Avro serialisers is definitely something I'd like to do - I have a (kind of abandoned) work-in-progress PR for Vulcan at https://github.com/fd4s/vulcan/pull/289 so if you feel like collaborating on it that would be great!
