### ISSUE TITLE
Thread naming strategy

### ISSUE THREAD

**Issue by TimWSpence** [fd4s/fs2-kafka#693]
Is there a reason why we append the thread id to the thread name [here](https://github.com/fd4s/fs2-kafka/blob/ab3665cd7ec1c6eba1d0626e435ba9da35fec1de/modules/core/src/main/scala/fs2/kafka/internal/Blocking.scala#L36)?

We saw `fs2-kafka-consumer-78` and were worried that we'd messed up our threadpools and that the kafka actor wasn't running on a pool of size 1

**Comment by bplommer** [comment]
I guess to ensure the name is unique when there are multiple consumers? @vlovgr would know. But I think we could replace that with a global `AtomicLong` counter - a mildly unpleasant thing to do but I don't foresee it causing any problems.

**Comment by vlovgr** [comment]
It is just to ensure uniqueness, yes. Feel free to raise a pull request with indexed-based numbering.
